version: 2.1

jobs:
  push-wiki:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Full clone source repo
          command: |
            git clone https://${GITHUB_API_KEY}@github.com/NikSignjarZilavec/VirtualEstate-Wiki.git source
      - run:
          name: Push to original project wiki
          working_directory: source
          command: |
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "${GITHUB_USERNAME}"
            git remote set-url origin https://${GITHUB_API_KEY}@github.com/andrej-nemanic/VirtualEstate_Project.wiki.git
            git push --force origin main:master

workflows:
  main-workflow:
    jobs:
      - push-wiki:
          filters:
            branches:
              only:
                - main